CREATE TABLE ENCOMENDA
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENTE INT,
	DATAENCOMENDA DATE,
	DATAENTREGA DATE,
	COBRAFRETE BOOLEAN,
	VALOR NUMERIC(11,2),
	VALORFRETE NUMERIC(11,2),
	VALORTOTAL NUMERIC(11,2),
	STATUS CHAR(1),
	CONSTRAINT FK_ENCOMENDA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
);