CREATE TABLE ENDERECO_CLIENTE
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENTE INT,
	ID_ENDERECO INT,
	CONSTRAINT FK_ENDERECO_CLIENTE_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID),
	CONSTRAINT FK_ENDERECO_CLIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);