CREATE TABLE PRODUTO_COMPOSICAO
(
	ID SERIAL PRIMARY KEY,
	ID_PRODUTO INT,
	QUANTIDADE NUMERIC(11,2),
	DESCRICAO CHAR(45),
	OBSERVACAO CHAR(100),
	CONSTRAINT FK_PRODUTO_COMPOSICAO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);